---
- name: Install Prometheus and Grafana
  hosts: all
  become: yes

  vars:
    prometheus_version: "2.52.0"
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_install_dir: /opt/prometheus
    prometheus_data_dir: /opt/prometheus/data

  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - tar
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Create Prometheus user and group
      user:
        name: "{{ prometheus_user }}"
        shell: /bin/false
        create_home: no
        system: yes

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
      loop:
        - prometheus
        - promtool

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"
        - /etc/prometheus

    - name: Copy Prometheus config
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'

    - name: Set ownership for Prometheus directories
      file:
        path: "{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: yes
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"
        - /etc/prometheus

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data_dir }}

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
